export const TASK_TITLE_PLACEHOLDERS = [
  'Estudar Trigonometria',
  'Revisar Genética',
  'Praticar Redação',
  'Resolver exercícios de Porcentagem',
  'Estudar Revolução Francesa',
  'Revisar Guerra Fria',
  'Estudar Células Procariontes e Eucariontes',
  'Resolver exercícios de Eletricidade',
  'Revisar Ligações Químicas',
  'Estudar Placas Tectônicas',
  'Praticar Interpretação de Texto',
  'Revisar Funções Matemáticas',
  'Estudar Probabilidade',
  'Resolver questões de Geometria',
  'Revisar Ecologia',
  'Estudar Era Vargas',
  'Praticar Inglês',
  'Fazer Simulado Fatec',
  'Fazer Simulado ENEM',
  'Revisar conteúdos de Física',
  'Estudar Sistema Sanguíneo',
  'Resolver lista de Química',
  'Revisar Gramática',
  'Estudar Brasil Colônia',
  'Praticar Raciocínio Lógico',
  'Revisar Estatística',
  'Estudar Fotossíntese',
  'Resolver exercícios de Cinemática',
  'Revisar Geografia do Brasil',
  'Estudar para a prova de Matemática',
  'Estudar APIs REST',
  'Revisar lógica de programação',
  'Praticar SQL',
  'Estudar bancos de dados',
  'Revisar conceitos de Git',
  'Estudar segurança de aplicações',
  'Praticar algoritmos',
  'Revisar arquitetura de software',
  'Estudar redes de computadores',
  'Praticar programação com JavaScript',
  'Revisar conceitos de orientação a objetos',
  'Estudar testes automatizados',
  'Estudar memória e aprendizagem',
  'Revisar emoções e comportamento',
  'Estudar desenvolvimento humano',
  'Revisar ansiedade e estresse',
  'Estudar teorias da personalidade',
  'Revisar comunicação e relações humanas',
  'Estudar anatomia básica',
  'Revisar sistema cardiovascular',
  'Estudar sistema respiratório',
  'Revisar sistema nervoso',
  'Estudar primeiros socorros',
  'Revisar alimentação e metabolismo',
  'Estudar funcionamento do coração',
  'Revisar imunidade e doenças',
  'Estudar tipos de solo',
  'Revisar irrigação',
  'Estudar nutrição das plantas',
  'Revisar pragas agrícolas',
  'Estudar cultivo sustentável',
  'Revisar fertilização do solo',
  'Estudar rotação de culturas',
  'Estudar resistência dos materiais',
  'Revisar circuitos elétricos',
  'Estudar estruturas',
  'Revisar desenho técnico',
  'Estudar mecânica básica',
  'Revisar materiais de construção',
  'Estudar processos de produção',
  'Estudar gestão financeira',
  'Revisar fluxo de caixa',
  'Estudar marketing digital',
  'Revisar planejamento estratégico',
  'Estudar empreendedorismo',
  'Revisar gestão de projetos',
  'Estudar princípios da Constituição',
  'Revisar direitos do consumidor',
  'Estudar contratos',
  'Revisar organização do Estado',
  'Estudar direitos trabalhistas',
  'Estudar inflação',
  'Revisar oferta e demanda',
  'Estudar juros',
  'Revisar economia básica',
  'Estudar mercado financeiro',
  'Estudar teoria das cores',
  'Revisar tipografia',
  'Estudar experiência do usuário',
  'Revisar princípios de interface',
  'Estudar composição visual',
  'Praticar conversação em inglês',
  'Revisar vocabulário em espanhol',
  'Estudar gramática em inglês',
  'Praticar leitura em outro idioma',
  'Revisar pronúncia',
  'Aprender matemática financeira',
  'Estudar astronomia básica',
  'Revisar história mundial',
  'Praticar desenho',
  'Aprender organização pessoal',
  'Estudar sustentabilidade',
  'Revisar filosofia',
  'Praticar escrita criativa',
  'Entender mudanças climáticas',
  'Preparar uma apresentação',
  'Estudar finanças pessoais',
  'Aprender noções de música',
] as const;

export const TASK_DESCRIPTION_PLACEHOLDERS = [
  'Revisar ângulos notáveis e a circunferência trigonométrica.',
  'Revisar teoria e resolver alguns exercícios',
  'Focar nos pontos em que tenho mais dificuldade',
  'Estudar o conteúdo e fazer questões depois',
  'Revisar minhas anotações e praticar',
  'Assistir uma aula e resolver exercícios',
  'Preparar o conteúdo para a próxima prova',
  'Entender os conceitos principais e praticar depois',
  'Revisar o conteúdo e anotar os pontos mais importantes',
  'Focar no que ainda não ficou claro',
  'Estudar a teoria e aplicar em exemplos práticos',
  'Revisar o conteúdo e testar o que aprendi',
  'Avançar neste assunto e revisar os pontos principais',
  'Separar um tempo para entender melhor esse tema',
  'Ler o material e resumir as ideias principais',
  'Praticar um pouco e conferir as respostas',
  'Organizar minhas anotações antes de começar',
  'Retomar o assunto e tirar as dúvidas principais',
  'Aprender os pontos básicos e avançar aos poucos',
  'Fazer uma revisão rápida e resolver questões',
  'Estudar com calma e registrar o que aprendi',
  'Preparar um resumo para consultar depois',
] as const;

export interface TaskPlaceholders {
  title: (typeof TASK_TITLE_PLACEHOLDERS)[number];
  description: (typeof TASK_DESCRIPTION_PLACEHOLDERS)[number];
}

function randomItem<const T>(items: readonly T[], random: () => number): T {
  return items[Math.floor(random() * items.length)] as T;
}

export function createTaskPlaceholders(
  random: () => number = Math.random,
): TaskPlaceholders {
  return {
    title: randomItem(TASK_TITLE_PLACEHOLDERS, random),
    description: randomItem(TASK_DESCRIPTION_PLACEHOLDERS, random),
  };
}
